version: "3.9"
services:
  simplebank-db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_SOURCE=postgresql://root:secret@simplebank-db:5432/simple_bank?sslmode=disable
    depends_on:
      - simplebank-db
    entrypoint:
      ["/app/wait-for.sh", "simplebank-db:5432", "--", "/app/start.sh"]

    command: ["/app/main"]
