version: "3.9"
services:
  simplebank-db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  # redis
  redis:
    image: 'redis:7-alpine'
    ports:
      - "6379:6379"
    restart: always


  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_SOURCE=postgresql://root:secret@simplebank-db:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
      - ENVIRONMENT=production
    depends_on:
      - simplebank-db
      - redis
    entrypoint:
      ["/app/wait-for.sh", "simplebank-db:5432", "--", "/app/start.sh"]

    command: ["/app/main"]
